plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.4'
    id 'io.spring.dependency-management' version '1.1.7'

    id 'checkstyle'
    id 'com.diffplug.spotless' version '8.10.3'
}

// Project
group = 'com.commerce'
version = '0.0.1-SNAPSHOT'
description = 'pagopa'

def queryDslVersion = "7.1"
def querydslSrcDir = layout.buildDirectory.dir("generated/querydsl").get().asFile

ext {
    set('springModulithVersion', "2.0.8")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
    }
}

// Dependencies
dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Infra
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'net.logstash.logback:logstash-logback-encoder:9.0'

    // Spring Modulith
    implementation 'org.springframework.modulith:spring-modulith-starter-jdbc'
    implementation "org.springframework.modulith:spring-modulith-starter-core"
    testImplementation "org.springframework.modulith:spring-modulith-starter-test"
    testImplementation "org.springframework.modulith:spring-modulith-docs"

    // Azure Blob Storage
    implementation 'com.azure.spring:spring-cloud-azure-starter-storage-blob:7.1.0'

    // AWS SDK S3
    implementation 'software.amazon.awssdk:s3:2.55.11'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // DB
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'net.datafaker:datafaker:2.5.4'
    runtimeOnly 'com.mysql:mysql-connector-j'

    // QueryDSL
    implementation("io.github.openfeign.querydsl:querydsl-core:${queryDslVersion}")
    implementation("io.github.openfeign.querydsl:querydsl-jpa:$queryDslVersion")
    annotationProcessor("io.github.openfeign.querydsl:querydsl-apt:$queryDslVersion:jpa")

    // Flyway
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    runtimeOnly 'org.flywaydb:flyway-mysql'

    // API Specification (Swagger API)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    // Thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-mysql'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// Test
tasks.named('test') {
    useJUnitPlatform()
    systemProperty(
            'spring.modulith.detection-strategy',
            'explicitly-annotated'
    )
}

// QueryDSL
sourceSets {
    main {
        java {
            srcDirs += querydslSrcDir
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.getGeneratedSourceOutputDirectory().set(file(querydslSrcDir))
}

// Code quality
spotless {
    java {
        target 'src/main/java/**/*.java', 'src/test/java/**/*.java'
        eclipse('4.26').configFile('config/spotless/eclipse-java-formatter.properties')
        importOrder(
                'java',
                'javax',
                'jakarta',
                'org.springframework',
                'org',
                'net',
                'io',
                'com.fasterxml',
                'com.querydsl',
                'lombok',
                'com',
                '',
                'com.commerce.pagopa',
                '\\#')
        removeUnusedImports()
        formatAnnotations()
        leadingTabsToSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }
}

checkstyle {
    toolVersion = '14.3.0'
    configFile = file('config/checkstyle/checkstyle.xml')
    ignoreFailures = false
    maxWarnings = 0
}

tasks.named('checkstyleMain') {
    setSource(fileTree('src/main/java'))
    configProperties = [
            methodNameFormat: '^[a-z][a-zA-Z0-9]*$'
    ]
}

tasks.named('checkstyleTest') {
    setSource(fileTree('src/test/java'))
    configProperties = [
            methodNameFormat: '^[a-zA-Z가-힣][a-zA-Z0-9가-힣]*(?:_[a-zA-Z0-9가-힣]+)*$'
    ]
}
