# Fluentd configuration

<source>
  @type tcp
  port 24224
  bind 0.0.0.0
  tag spring.boot
  <parse>
    @type json
  </parse>
</source>

<match spring.boot>
  @type copy
  <store>
    @type stdout
  </store>

  <store>
    @type elasticsearch
    host elasticsearch
    port 9200
    logstash_format true
    logstash_prefix springboot-logs
    logstash_dateformat %Y%m%d
    suppress_type_name true
    verify_es_version_at_startup false
    default_elasticsearch_version 8
    include_tag_key true
    tag_key @log_name
    <buffer>
      flush_interval 5s
      flush_thread_count 2
    </buffer>
  </store>
</match>
